cities/urls.py
from django.urls import path
from cities.views import *

urlpatterns = [
    # path('', home, name='home'),
    path('', CityListView.as_view(), name='home'),
    path('detail/<int:pk>/', CityDetailView.as_view(), name='detail'),
    path('update/<int:pk>/', CityUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', CityDeleteView.as_view(), name='delete'),
    path('add/', CityCreateView.as_view(), name='create'),
]

travel/urls.py
from django.contrib import admin
from django.urls import path, include

from routes.views import home, find_routes, add_route, save_route, RouteListView, RouteDetailView, RouteDeleteView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cities/', include(('cities.urls', 'cities'))),
    path('planes/', include(('planes.urls', 'planes'))),
    path('accounts/', include(('accounts.urls', 'accounts'))),
    path('', home, name="home"),
    path('find_routes/', find_routes, name="find_routes"),
    path('add_route/', add_route, name="add_route"),
    path('save_route/', save_route, name="save_route"),
    path('list/', RouteListView.as_view(), name='list'),
    path('detail/<int:pk>/', RouteDetailView.as_view(), name='detail'),
    path('delete/<int:pk>/', RouteDeleteView.as_view(), name='delete'),
    # path('about/', about),
]

routes/models.py
from django.db import models

from cities.models import City


class Route(models.Model):
    name = models.CharField(
        max_length=50, unique=True, verbose_name='Route name'
    )
    travel_times = models.PositiveSmallIntegerField(
        verbose_name='Travel Time'
    )
    from_city = models.ForeignKey(
        City, on_delete=models.CASCADE,
        related_name='route_from_city_set',
        verbose_name='Departing from a city'
    )
    to_city = models.ForeignKey(
        'cities.City', on_delete=models.CASCADE,
        related_name='route_to_city_set',
        verbose_name='Arriving in a city'
    )
    planes = models.ManyToManyField(
        'planes.Plane', verbose_name='List of Planes'
    )

    def __str__(self):
        return f'Route number {self.name} from {self.from_city} to {self.to_city}'

    class Meta:
        verbose_name = 'Route'
        verbose_name_plural = 'Routes'
        ordering = ['travel_times']

templates/about.html
{% extends 'base.html' %}
{% block title %}About{% endblock %}
{% block content %}
<h1>About us!</h1>
{% endblock %}

templates/base.html
{% url 'cities:home' as cities_home_url %}
{% url 'cities:create' as cities_create_url %}
{% url 'planes:home' as planes_home_url %}
{% url 'planes:create' as planes_create_url %}
{% url 'list' as route_list %}
{% url 'detail' as route_detail %}

<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css"
          integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet"/>

    <title>{% block title %}{% endblock %}</title>
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-light container" style="background-color: skyblue;">
    <a class="navbar-brand" href="{% url 'home' %}">AirOne </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
            aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item {% if request.path == cities_home_url%} active {% endif %}">
                <a class="nav-link" href="{% url 'cities:home' %}"> Cities <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item {% if request.path == planes_home_url%} active {% endif %}">
                <a class="nav-link" href="{% url 'planes:home' %}">Planes</a>
            </li>
            <li class="nav-item {% if request.path == route_list%} active {% endif %} ">
                <a class="nav-link" href="{% url 'list' %}">Routes</a>
            </li>

            {% if user.is_authenticated%}
            <li class="nav-item dropdown
            {% if request.path == cities_create_url or request.path == planes_create_url%} active {% endif %}"
            >
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button"
                   data-toggle="dropdown" aria-expanded="false">
                    Add
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                    <a class="dropdown-item" href="{% url 'cities:create' %}">Add New City</a>
                    <a class="dropdown-item" href="{% url 'planes:create' %}">Add New Plane</a>
                </div>
            </li>
            {% else %}
            <li class="nav-item" ><a href="" class="nav-link disabled">Add</a></li>
            {% endif %}

            {% if user.is_authenticated%}
            <li class="nav-item ">
                <a class="nav-link" href="{% url 'accounts:logout'%}">Logout</a>
            </li>
            {% else %}
            <li class="nav-item ">
                <a class="nav-link" href="{% url 'accounts:login'%}">Login</a>
            </li>
            <li class="nav-item ">
                <a class="nav-link" href="{% url 'accounts:registration'%}">Register</a>
            </li>
            {% endif %}

        </ul>
    </div>
</nav>

<div class="container">
    <div class="row">
        <div class="col-md-8 mx-auto my-4">
            {% if messages %}

            {% for message in messages %}

            {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                {{ message }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            {% else %}
            <div class="alert alert-success alert-dismissible fade show" role="alert">
                {{ message }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            {% endif %}

            {% endfor %}

            {% endif %}
        </div>
    </div>
</div>

<div class="container">
    {% block content %}{% endblock %}
</div>


<!-- Optional JavaScript; choose one of the two! -->

<!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-fQybjgWLrvvRgtW6bFlB7jaZrFsaBXjsOMm/tB9LTS58ONXgqbR9W8oWht/amnpF"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>


<!-- Option 2: Separate Popper and Bootstrap JS -->
<!--
<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.min.js" integrity="sha384-VHvPCCyXqtD5DqJeNxl2dtTyhF78xXNXdkwX1CZeRusQfRKp+tA7hAShOK/B/fQ2" crossorigin="anonymous"></script>
-->
<script>
    $(document).ready(function() {
        $('.js-example-basic-single').select2();
        $('.js-example-basic-multiple').select2();
    });

</script>
</body>

templates/form.html
<div class="row">
    <div class="col-md-4">
        <form action="{{ action }}" method="post"> {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">{{ button }}</button>
        </form>
    </div>
</div>

templates/home.html
{% extends 'base.html' %}
{% block title %}Home{% endblock %}
{% block content %}
<h1>Hello {{name}}!</h1>
{% endblock %}